Repository Laravel-Backpack/docs, pull requests merged in 2023-03, with the labels that each got.

#413 added example 12
  5.x/crud-fields-javascript-api.md
Labels: Priority: SHOULD

#387 Widget Section for Operations
  5.x/crud-operation-create.md
  5.x/crud-operation-list-entries.md
  5.x/crud-operation-reorder.md
  5.x/crud-operation-show.md
  5.x/crud-operation-update.md
Labels: Priority: SHOULD

#395 [Feature Request] Allow delete button on edit page
  5.x/crud-operation-update.md
Labels: enhancement, Priority: SHOULD

#416 add note about dropdown buttons
  5.x/crud-operation-list-entries.md
Labels: Priority: MUST
