Repository Laravel-Backpack/docs, pull requests merged in 2023-08, with the labels that each got.

#493 add note about uploaders in relationships
  6.x/crud-uploaders.md
Labels: bug, Priority: MUST

#496 Add `attribute` in relationship field pivot select example
  6.x/crud-fields.md
Labels: Priority: MUST, documentation, Size: XS

#492 make filter docs use fluent syntax by default
  6.x/crud-filters.md
Labels: Priority: MUST

#503 add email validation
  6.x/base-how-to.md
Labels: Priority: MUST

#505 mention nested dropdowns
  6.x/base-components.md
Labels: Priority: SHOULD
