Repository Laravel-Backpack/docs, pull requests merged in 2023-06, with the labels that each got.

#437 Add v6 columns to the docs.
  6.x/crud-columns.md
Labels: Priority: MUST

#438 Add Left Columns to Docs
  6.x/crud-columns.md
Labels: enhancement, Priority: MUST

#441 add docs for menu components in v6
  6.x/base-components.md
  6.x/crud-tutorial.md
  6.x/index.md
  6.x/upgrade-guide.md
Labels: Priority: MUST, Size: XS

#443 add new videos to v6 docs
  6.x/getting-started-videos.md
Labels: Priority: MUST, Size: S

#444 Add checklist_dependency column to docs
  6.x/crud-columns.md
Labels: Priority: MUST, documentation

#447 add docs on how to create a new backpack theme
  6.x/add-ons-tutorial-how-to-create-a-theme.md
  6.x/index.md
Labels: Priority: MUST, Priority: SHOULD, Size: S

#446 remove color picker from docs
  6.x/crud-columns.md
  6.x/crud-fields.md
  6.x/release-notes.md
  6.x/upgrade-guide.md
Labels: Priority: MUST

#449 Put Links & Description to Videos docs page
  6.x/getting-started-videos.md
Labels: enhancement, Priority: MUST, documentation
